name: blood
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_onboarding_slider: ^1.0.11
  flutter_svg: ^2.0.10+1
  phone_text_field: ^0.0.7
  otp_pin_field: ^1.2.2
  flutter_otp_text_field: ^1.1.1
  animated_bottom_navigation_bar: ^1.3.3
  animate_do: ^3.3.4
  switcher_button: ^0.0.4
  custom_radio_grouped_button: ^2.2.1
  flutter_form_builder: ^9.2.0
  form_builder_validators: ^9.0.0
  chat_bubbles: ^1.5.0
  font_awesome_flutter: ^10.7.0
  google_maps_flutter: ^2.5.3
  interactive_bottom_sheet: ^1.0.0
  rflutter_alert: ^2.0.7
  flutter_bloc: ^8.1.5
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0
  flutter_secure_storage: ^9.0.0
  get_it: ^8.0.0
  form_builder_phone_field: ^2.0.1
  phone_form_field: ^8.1.0
  intl: ^0.18.1  # versão compatível com phone_form_field
  loading_animation_widget: ^1.2.1
  simple_fontellico_progress_dialog: ^0.3.0
  quickalert: ^1.1.0
  cool_alert: ^2.0.1
  ndialog: ^4.3.1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  skeletonizer: ^1.0.1
  google_places_flutter: ^2.0.8
  searchable_paginated_dropdown: ^1.3.0
  select_dialog: ^2.0.1
  animations: ^2.0.11
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  get: ^4.6.6
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 900
